jobs:
  backport-issue:
    secrets:
      GH_ACTIONS_REPO_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    uses: spring-io/spring-github-workflows/.github/workflows/spring-backport-issue.yml@main
name: Backport Issue
on:
  repository_dispatch:
    types: trigger-ga___backport-issue.yml
