concurrency:
  cancel-in-progress: true
  group: group-snapshot-for-${{ github.ref }}
jobs:
  build-snapshot:
    secrets:
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
        }}
      GRADLE_ENTERPRISE_CACHE_USER: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
      GRADLE_ENTERPRISE_SECRET_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY
        }}
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-gradle-snapshot.yml@main
    with:
      gradleTasks: ${{ github.event_name == 'schedule' && '--rerun-tasks' || '' }}
name: CI SNAPSHOT
on:
  repository_dispatch:
    types: trigger-ga___ci-snapshot.yml
