jobs:
  dispatch-docs-build:
    if: github.repository_owner == 'spring-projects'
    uses: spring-io/spring-github-workflows/.github/workflows/spring-dispatch-docs-build.yml@main
name: Deploy Docs
on:
  repository_dispatch:
    types: trigger-ga___deploy-docs.yml
permissions:
  actions: write
