jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@main
    with:
      mergeArguments: --auto --squash
name: Merge Dependabot PR
on:
  repository_dispatch:
    types: trigger-ga___merge-dependabot-pr.yml
run-name: Merge Dependabot PR ${{ github.ref_name }}
