jobs:
  build-pull-request:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-gradle-pull-request-build.yml@main
name: Pull Request Build
on:
  repository_dispatch:
    types: trigger-ga___pr-build.yml
